"""Constants."""

ANSWER_NORM = {
    "yes": "present",
    "y": "present",
    "yep":"present",
    "yup": "present",
    "definitely": "present",
    "sure": "present",
    "surely": "present",
    "present": "present",
    "no": "absent",
    "n": "absent",
    "nah": "absent",
    "nope": "absent",
    "absent": "absent",
    "somewhat": "unknown",
    "sometimes": "unknown",
    "?": "unknown",
    "skip": "unknown",
    "unknown": "unknown",
    "donno": "unknown",
    "dont know": "unknown",
    "don't know": "unknown",
}
